kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-react-pv
  labels: #Labels 
      app: postgres
      ver: postgres-react-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
      server: 10.100.102.53
      path: "/mnt/react_demo"
