---
apiVersion: v1
kind: Namespace
metadata:
  name: react-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-deployment
  namespace: react-demo
  labels:
    app: react-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
      - name: react-demo
        image: "joshuagoldman1994/react-demo:1.0.0"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-demo-service
  namespace: react-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: react-demo

            
